name: Limit PR line changes

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  check_pr_size:
    if: github.base_ref == 'main' && startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Count lines of code changed
        id: line_count
        run: |
          # LINES_ADDED=$(git diff --shortstat origin/${{ github.base_ref }}...HEAD | awk '{print $4}')
          # LINES_DELETED=$(git diff --shortstat origin/${{ github.base_ref }}...HEAD | awk '{print $6}')
          LINES_CHANGED=$(git diff --name-only ${{ github.base_ref}} ${{ github.sha }})
          echo "Total lines changed: $LINES_CHANGED"
          echo "::set-output name=lines_changed::$LINES_CHANGED"

      - name: Fail if too many lines are changed
        run: |
          if [ ${{ steps.line_count.outputs.lines_changed }} -gt 10 ]; then
            echo "Too many lines changed: ${{ steps.line_count.outputs.lines_changed }} (max 10)"
            exit 1
          else
            echo "Line changes within limit: ${{ steps.line_count.outputs.lines_changed }} (max 10)"
          fi

