name: Limit PR line changes

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  check_pr_size:
    if: github.base_ref == 'main' && startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Count lines of code changed
        id: line_count
        run: |
          # Fetch the main branch to compare
          git fetch origin main:main
          # Calculate the diff
          ADDED_LINES=$(git diff --shortstat origin/main...HEAD | awk '{print $4}')
          DELETED_LINES=$(git diff --shortstat origin/main...HEAD | awk '{print $6}')
          TOTAL_LINES=$((ADDED_LINES + DELETED_LINES))
          echo "Total lines changed: $TOTAL_LINES"
          echo "ADDED_LINES=$ADDED_LINES" >> $GITHUB_ENV
          echo "DELETED_LINES=$DELETED_LINES" >> $GITHUB_ENV
          echo "TOTAL_LINES=$TOTAL_LINES" >> $GITHUB_ENV

      - name: Fail if too many lines are changed
        run: |
          if [ ${{ env.TOTAL_LINES }} -gt 10 ]; then
            echo "Too many lines changed: ${{ env.TOTAL_LINES }} (max 10)"
            exit 1
          else
            echo "Line changes within limit: ${{ env.TOTAL_LINES }} (max 10)"
          fi

